import type { Candidate, Changeset, Evidence, User } from "./types";

/** Split a quote on `|` — odd segments are the matched span. */
const P = (s: string) => s.split("|").map((text, i) => ({ text, mark: i % 2 === 1 }));

const ev = (
	q: string,
	path: string,
	url: string,
	when: string,
	kind: string,
	conf: number,
): Evidence => ({
	parts: P(q),
	path,
	url,
	when,
	kind,
	conf,
});

/** The fixtures spell an object's untouched tags as `k=v  k=v`, or a dash for none. */
type SeedCandidate = Omit<Candidate, "allQuarantined" | "hasNoEv" | "hasInvalid" | "unchanged"> & {
	unchanged: string;
};

const unchangedTags = (text: string) =>
	text === "—"
		? []
		: text.split(/\s{2,}/).map((pair) => {
				const eq = pair.indexOf("=");
				return { k: pair.slice(0, eq), v: pair.slice(eq + 1) };
			});

const SEED: SeedCandidate[] = [
	{
		id: "c1",
		osmId: "node/2714490831",
		type: "update",
		name: "Boulangerie Gaubert",
		addr: "12 Rue du Taur, 31000 Toulouse",
		lat: 43.6058,
		lon: 1.4432,
		source: "website",
		conf: 0.81,
		version: 4,
		fetched: "02-09-2026",
		age: "12d",
		nearby: ["18 m  shop=bakery (unnamed)", "41 m  amenity=cafe  Le Taur"],
		unchanged:
			"name=Boulangerie Gaubert  shop=bakery  addr:housenumber=12  addr:street=Rue du Taur",
		tags: [
			{
				op: "add",
				k: "phone",
				v: "+33 5 61 21 06 32",
				conf: 0.97,
				ev: ev(
					"Commandes au |05 61 21 06 32| — retrait en boutique",
					"/contact",
					"https://example.invalid/contact",
					"12d ago",
					"verbatim",
					0.97,
				),
			},
			{
				op: "mod",
				k: "opening_hours",
				v: "Tu-Sa 07:00-19:30; Su 07:00-13:00",
				was: "Mo-Sa 07:00-20:00",
				conf: 0.81,
				ev: ev(
					"Ouvert du |mardi au samedi 7h–19h30|, |dimanche 7h–13h|. Fermé le lundi.",
					"/",
					"https://example.invalid/",
					"12d ago",
					"paraphrase fr",
					0.81,
				),
			},
			{ op: "add", k: "takeaway", v: "yes", conf: 0.44, ev: null },
		],
	},
	{
		id: "c2",
		osmId: "new node",
		type: "new",
		name: "Café Sept",
		addr: "7 Place Saint-Georges, 31000 Toulouse",
		lat: 43.6041,
		lon: 1.447,
		source: "sirene",
		conf: 0.93,
		version: 0,
		fetched: "09-09-2026",
		age: "5d",
		nearby: ["26 m  amenity=cafe  Le Saint-Georges", "60 m  amenity=restaurant"],
		unchanged: "—",
		tags: [
			{
				op: "add",
				k: "amenity",
				v: "cafe",
				conf: 0.95,
				ev: ev(
					"activité principale : |débits de boissons| (56.30Z)",
					"sirene:90241377800017",
					"https://example.invalid/sirene",
					"5d ago",
					"dataset row",
					0.95,
				),
			},
			{
				op: "add",
				k: "name",
				v: "Café Sept",
				conf: 0.99,
				ev: ev(
					"enseigne1Etablissement: |CAFE SEPT|",
					"sirene:90241377800017",
					"https://example.invalid/sirene",
					"5d ago",
					"dataset row",
					0.99,
				),
			},
			{
				op: "add",
				k: "addr:housenumber",
				v: "7",
				conf: 0.98,
				ev: ev(
					"numeroVoieEtablissement: |7| / typeVoie: PLACE",
					"sirene:90241377800017",
					"https://example.invalid/sirene",
					"5d ago",
					"dataset row",
					0.98,
				),
			},
			{
				op: "add",
				k: "ref:FR:SIRET",
				v: "90241377800017",
				conf: 0.99,
				ev: ev(
					"siret: |90241377800017|",
					"sirene:90241377800017",
					"https://example.invalid/sirene",
					"5d ago",
					"dataset row",
					0.99,
				),
			},
		],
	},
	{
		id: "c3",
		osmId: "node/303119844",
		type: "update",
		name: "Ombres Blanches",
		addr: "50 Rue Gambetta, 31000 Toulouse",
		lat: 43.604,
		lon: 1.4415,
		source: "website",
		conf: 0.88,
		version: 11,
		fetched: "11-09-2026",
		age: "3d",
		nearby: ["33 m  shop=books (unnamed)", "75 m  amenity=cafe  Ombres Blanches Café"],
		unchanged: "name=Ombres Blanches  shop=books  website=https://ombres-blanches.fr",
		tags: [
			{
				op: "mod",
				k: "opening_hours",
				v: "Mo-Sa 10h-19h; dim ferme",
				was: "Mo-Sa 10:00-19:00",
				conf: 0.88,
				invalid: true,
				invalidMsg: 'unexpected token "h" at position 9',
				invalidHint:
					'expected HH:MM. "dim" is not a valid weekday abbreviation — use Su. Upload blocked until corrected upstream.',
				ev: ev(
					"Librairie ouverte du |lundi au samedi de 10h à 19h|, fermée le dimanche.",
					"/infos-pratiques",
					"https://example.invalid/infos",
					"3d ago",
					"paraphrase fr",
					0.88,
				),
			},
		],
	},
	{
		id: "c4",
		osmId: "node/1188204471",
		type: "closure",
		name: "Pharmacie du Capitole",
		addr: "9 Place du Capitole, 31000 Toulouse",
		lat: 43.6042,
		lon: 1.4445,
		source: "sirene",
		conf: 0.71,
		version: 8,
		fetched: "07-09-2026",
		age: "7d",
		nearby: ["120 m  amenity=pharmacy  Pharmacie Lafayette", "210 m  amenity=pharmacy"],
		unchanged: "name=Pharmacie du Capitole  addr:housenumber=9",
		tags: [
			{
				op: "mod",
				k: "disused:amenity",
				v: "pharmacy",
				was: "amenity=pharmacy",
				conf: 0.71,
				ev: ev(
					"etatAdministratifEtablissement: |F| (fermé) — dateFin |31-07-2026|",
					"sirene:34028744500021",
					"https://example.invalid/sirene",
					"7d ago",
					"dataset row",
					0.71,
				),
			},
			{
				op: "del",
				k: "opening_hours",
				v: "Mo-Fr 08:30-19:30; Sa 09:00-13:00",
				conf: 0.71,
				ev: ev(
					"establishment marked |closed| — hours no longer applicable",
					"sirene:34028744500021",
					"https://example.invalid/sirene",
					"7d ago",
					"derived",
					0.71,
				),
			},
			{
				op: "del",
				k: "phone",
				v: "+33 5 61 21 09 73",
				conf: 0.71,
				ev: ev(
					"establishment marked |closed|",
					"sirene:34028744500021",
					"https://example.invalid/sirene",
					"7d ago",
					"derived",
					0.71,
				),
			},
		],
	},
	{
		id: "c5",
		osmId: "node/4418820071",
		type: "update",
		name: "Le Bibent",
		addr: "5 Place du Capitole, 31000 Toulouse",
		lat: 43.6046,
		lon: 1.4443,
		source: "website",
		conf: 0.9,
		version: 7,
		fetched: "10-09-2026",
		age: "4d",
		conflict: true,
		baseVersion: 7,
		headVersion: 8,
		conflictWho: "user:tlse_mapper, 3 h ago, changeset 154819902",
		theirs: [
			{ k: "opening_hours", v: "Tu-Su 12:00-14:30,19:00-22:30" },
			{ k: "phone", v: "+33 5 34 30 18 37" },
			{ k: "cuisine", v: "french" },
		],
		ours: [
			{ k: "opening_hours", v: "Tu-Su 12:00-14:00,19:00-23:00" },
			{ k: "website", v: "https://bibent.fr" },
		],
		nearby: ["40 m  amenity=restaurant", "95 m  amenity=bar"],
		unchanged: "name=Le Bibent  amenity=restaurant  cuisine=french",
		tags: [
			{
				op: "mod",
				k: "opening_hours",
				v: "Tu-Su 12:00-14:00,19:00-23:00",
				was: "Tu-Su 12:00-14:30,19:00-22:30",
				conf: 0.9,
				ev: ev(
					"Service |12h–14h| et |19h–23h|, du mardi au dimanche.",
					"/horaires",
					"https://example.invalid/horaires",
					"4d ago",
					"paraphrase fr",
					0.9,
				),
			},
			{
				op: "add",
				k: "website",
				v: "https://bibent.fr",
				conf: 0.99,
				ev: ev(
					"canonical: |https://bibent.fr|",
					"/",
					"https://example.invalid/",
					"4d ago",
					"verbatim",
					0.99,
				),
			},
		],
	},
	{
		id: "c6",
		osmId: "node/982211043",
		type: "update",
		name: "Boucherie Cazes",
		addr: "31 Rue de la Colombette, 31000 Toulouse",
		lat: 43.6082,
		lon: 1.4522,
		source: "website",
		conf: 0.76,
		version: 3,
		fetched: "14-06-2026",
		age: "92d",
		stale: 92,
		nearby: ["52 m  shop=butcher (unnamed)", "88 m  shop=greengrocer"],
		unchanged: "name=Boucherie Cazes  shop=butcher",
		tags: [
			{
				op: "mod",
				k: "opening_hours",
				v: "Tu-Sa 08:00-13:00,15:30-19:30",
				was: "Tu-Sa 08:00-19:30",
				conf: 0.76,
				ev: ev(
					"Ouvert |8h–13h| et |15h30–19h30| du mardi au samedi",
					"/",
					"https://example.invalid/",
					"92d ago",
					"paraphrase fr",
					0.76,
				),
			},
		],
	},
	{
		id: "c7",
		osmId: "node/5520193318",
		type: "update",
		name: "Épicerie Compans",
		addr: "4 Rue de Périole, 31500 Toulouse",
		lat: 43.6115,
		lon: 1.434,
		source: "website",
		conf: 0.38,
		version: 2,
		fetched: "08-09-2026",
		age: "6d",
		nearby: ["70 m  shop=convenience", "140 m  shop=supermarket  Carrefour City"],
		unchanged: "name=Épicerie Compans  shop=convenience",
		tags: [
			{ op: "add", k: "opening_hours", v: "Mo-Su 08:00-22:00", conf: 0.38, ev: null },
			{ op: "add", k: "phone", v: "+33 5 61 48 12 90", conf: 0.31, ev: null },
		],
	},
	{
		id: "c8",
		osmId: "new node",
		type: "new",
		name: "Fleuriste des Minimes",
		addr: "88 Avenue des Minimes, 31200 Toulouse",
		lat: 43.619,
		lon: 1.438,
		source: "sirene",
		conf: 0.95,
		version: 0,
		fetched: "12-09-2026",
		age: "2d",
		nearby: ["310 m  shop=florist", "45 m  shop=hairdresser"],
		unchanged: "—",
		tags: [
			{
				op: "add",
				k: "shop",
				v: "florist",
				conf: 0.96,
				ev: ev(
					"activité: |commerce de détail de fleurs| (47.76Z)",
					"sirene:81903244100019",
					"https://example.invalid/sirene",
					"2d ago",
					"dataset row",
					0.96,
				),
			},
			{
				op: "add",
				k: "name",
				v: "Fleuriste des Minimes",
				conf: 0.94,
				ev: ev(
					"enseigne1Etablissement: |FLEURISTE DES MINIMES|",
					"sirene:81903244100019",
					"https://example.invalid/sirene",
					"2d ago",
					"dataset row",
					0.94,
				),
			},
		],
	},
	{
		id: "c9",
		osmId: "node/771290112",
		type: "update",
		name: "Tabac des Carmes",
		addr: "2 Place des Carmes, 31000 Toulouse",
		lat: 43.5985,
		lon: 1.444,
		source: "website",
		conf: 0.88,
		version: 6,
		fetched: "13-09-2026",
		age: "1d",
		nearby: ["15 m  shop=tobacco", "62 m  amenity=bar"],
		unchanged: "name=Tabac des Carmes  shop=tobacco  addr:street=Place des Carmes",
		tags: [
			{
				op: "add",
				k: "phone",
				v: "+33 5 61 52 31 08",
				conf: 0.88,
				ev: ev(
					"Tél. |05 61 52 31 08|",
					"/contact",
					"https://example.invalid/contact",
					"1d ago",
					"verbatim",
					0.88,
				),
			},
		],
	},
	{
		id: "c10",
		osmId: "node/2201883901",
		type: "closure",
		name: "Coiffure Saint-Cyprien",
		addr: "17 Rue Réclusane, 31300 Toulouse",
		lat: 43.599,
		lon: 1.4308,
		source: "sirene",
		conf: 0.62,
		version: 5,
		fetched: "05-09-2026",
		age: "9d",
		nearby: ["80 m  shop=hairdresser", "190 m  shop=beauty"],
		unchanged: "name=Coiffure Saint-Cyprien",
		tags: [
			{
				op: "mod",
				k: "disused:shop",
				v: "hairdresser",
				was: "shop=hairdresser",
				conf: 0.62,
				ev: ev(
					"etatAdministratifEtablissement: |F| — dateFin |02-05-2026|",
					"sirene:50887342100014",
					"https://example.invalid/sirene",
					"9d ago",
					"dataset row",
					0.62,
				),
			},
		],
	},
];

export const CANDIDATES: Candidate[] = SEED.map((c) => ({
	...c,
	unchanged: unchangedTags(c.unchanged),
	allQuarantined: c.tags.every((t) => !t.ev),
	hasNoEv: c.tags.some((t) => !t.ev),
	hasInvalid: c.tags.some((t) => t.invalid),
}));

export const HISTORY: Changeset[] = (
	[
		[
			"154812204",
			"13-09-2026 21:04",
			"Toulouse POI updates from SIRENE + operator websites (reviewed)",
			"12 nodes",
			"ok",
			"154812204",
		],
		[
			"154799841",
			"12-09-2026 19:47",
			"Opening hours corrections, Capitole / Carmes",
			"7 nodes",
			"ok",
			"154799841",
		],
		["—", "11-09-2026 22:15", "Closures from SIRENE cessations", "4 nodes", "409", "154788019"],
		["154771330", "10-09-2026 20:32", "New POIs, Minimes / Compans", "9 nodes", "ok", "154771330"],
	] as const
).map((h) => ({
	id: h[0],
	url: `https://www.openstreetmap.org/changeset/${h[5]}`,
	when: h[1],
	comment: h[2],
	objects: h[3],
	result: h[4],
}));

// ── accounts ─────────────────────────────────────────────────────────────────
/** The people with access. Passwords are fixtures: a real deployment checks a
    hash server-side, and SSO-provisioned accounts have none at all. */
export const USERS: User[] = [
	{
		id: "u1",
		name: "Antoine Langlois",
		email: "antoine@antoine-langlois.net",
		role: "admin",
		initials: "AL",
		password: "review",
		osm: "alanglois",
		lastSeen: "14-09-2026 06:40",
	},
	{
		id: "u2",
		name: "Camille Roux",
		email: "camille@antoine-langlois.net",
		role: "reviewer",
		initials: "CR",
		password: "review",
		osm: "camroux",
		lastSeen: "13-09-2026 21:58",
	},
	{
		id: "u3",
		name: "Théo Marchand",
		email: "theo@antoine-langlois.net",
		role: "reviewer",
		initials: "TM",
		ssoOnly: true,
		osm: "theo-m",
		lastSeen: "11-09-2026 18:22",
	},
];

/** The preferences a new instance starts every account with. */
export const SETTINGS = {
	osmConnected: "12-09-2026 20:11",
	osmScopes: "write_api · read_prefs",
	osmComment: "",
	osmHashtag: "#poi-review",
	osmPerChangeset: 50,
	vim: true,
	confirmAccept: false,
	showHints: true,
};

/** The notification channels a new instance starts with. */
export const NOTIFICATIONS = {
	ntfyOn: true,
	ntfyServer: "https://ntfy.lan",
	ntfyTopic: "osm-review",
	webhookOn: false,
	webhookUrl: "",
	webhookSecret: "",
	emailOn: true,
	emailTo: "antoine@antoine-langlois.net",
	emailRelay: "smtp://smtp.lan:587",
	queueOver: 250,
	eventQueue: true,
	eventSourceFailed: true,
	eventUploadFailed: true,
	eventRunFinished: false,
};
